spring:
    application:
      name: ${server.hostname}
server:
    hostname: eurekaServer
    port: 1001
eureka:
    instance:
      #eureka服务器的标识，如果是集群就可以写成eurekaSer1,eurekaSer2,eurekaSer3..
      hostname: ${server.hostname}
    client:
      registerWithEureka: false
      fetchRegistry: false
      #开启客户端存活状态监测
      healthcheck:
        enabled: true
      serviceUrl:
        defaultZone: http://127.0.0.1:1001/eureka/


##配置端口
#server:
#  port: 8888
##配置为Eureka的服务端-服务注册中心
#eureka:
#  instance:
#    #eureka服务器的标识，如果是集群就可以写成 eurekaSer1,eurekaSer2,eurekaSer3..
#    hostname: localhost
#  client:
#    #因为自己是注册中心，设置为false，表示不向注册中心注册自己
#    register-with-eureka: false
#    #因为自己是注册中心，设置为false，表示不需要去检索服务
#    fetch-registry: false
#    #开启客户端存活状态监测
##    healthcheck:
##      enabled: true
#    #Eureka客户端将要注册的注册中心的地址
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/